### ISSUE TITLE
Add option to pass a custom location of the package.json in the no-uninstalled-addons rule

### ISSUE THREAD

**Issue by andrelas1** [storybookjs/eslint-plugin-storybook#101]
**Is your feature request related to a problem? Please describe.**
The `no-uninstalled-addons` rule does not provide a custom path for the package.json. It should provide that in the rule configuration.

**Describe the solution you'd like**
The solution would be to add a custom schema to this rule, where the location of the package.json can be specified in there.

**Describe alternatives you've considered**
That would be the best and most explicit option.

**Additional context**
No additional context.

**Comment by yannbf** [comment]
This was released in `0.6.2`. Thank you so much @andrelas1 !

**Comment by yannbf** [comment]
Could you share a way to reproduce that @coler-j ?
