### ISSUE TITLE
Bump @storybook/csf

### ISSUE THREAD

**Issue by janeklb** [storybookjs/eslint-plugin-storybook#128]
It is currently semi-pinned via 
```
"@storybook/csf": "^0.0.1"
```

which, by npm's semver implementation, will always remain less than `0.1.0` (which is the latest version https://www.npmjs.com/package/@storybook/csf)

**Comment by kasperpeulen** [comment]
Fixed by:
https://github.com/storybookjs/eslint-plugin-storybook/pull/171
