### ISSUE TITLE
Support for the new FlatConfig format

### ISSUE THREAD

**Issue by AndreaPontrandolfo** [storybookjs/eslint-plugin-storybook#135]
Any plans to support the new Eslint FlatConfig format, `eslint.config.js`?
In the next major release of Eslint, the new format is gonna be the default and the old format deprecated, so it should be updated.

**Comment by yannbf** [comment]
Hey there! Thanks for opening this issue.

Are you willing to contribute to make this happen? I'm happy to guide in the process if needed!

**Comment by waldemarfm** [comment]
@yannbf I'm interested in helping with this. I don't _think_ it'll be too complicated.

Would the approach be a major version bump and go all in on the change, or do we somehow offer support for both formats and make it opt-in for projects using flag configs?

**Comment by AndreaPontrandolfo** [comment]
I would love to contribute but i also have my hands-full with OSS projects right now.

**Comment by yannbf** [comment]
Hey @AndreaPontrandolfo @waldemarfm contributions are definitely welcome. If this change can be done in a backwards compatible way, that'd be definitely preferred! If you know what are the steps to support this format, describing those would already be quite helpful as well!

**Comment by xdebbie** [comment]
Do we have any new updates on this issue?

**Comment by yannbf** [comment]
Hey everyone! There is a canary version that introduced support to the flat config file while trying to maintain it backwards compatible. We are not 100% confident of merging it yet, so please give it a try:
```
npm install eslint-plugin-storybook@0.9.0--canary.156.da7873a.0
# or 
yarn add eslint-plugin-storybook@0.9.0--canary.156.da7873a.0
```

Feedback is truly appreciated.

**Comment by jerkovicl** [comment]
@yannbf  Tested on project and linting works with flat config, only thing to improve is types but that's already mentioned in [PR](https://github.com/storybookjs/eslint-plugin-storybook/pull/156#issuecomment-2121632667)

**Comment by Adamlb** [comment]
eslint-plugin-storybook@0.9.0--canary.156.da7873a.0 
Works for me with eslint 8.57

**Comment by bmulholland** [comment]
canary has been working for us with eslint 9 & flat config

**Comment by rikisamurai** [comment]
> Hey everyone! There is a canary version that introduced support to the flat config file while trying to maintain it backwards compatible. We are not 100% confident of merging it yet, so please give it a try:
> 
> ```
> npm install eslint-plugin-storybook@0.9.0--canary.156.da7873a.0
> # or 
> yarn add eslint-plugin-storybook@0.9.0--canary.156.da7873a.0
> ```
> 
> Feedback is truly appreciated.

hello，could you tell how to configure this plugin in the flat config？

**Comment by bmulholland** [comment]
`eslint.config.js`:
```
import eslintPluginStorybook from "eslint-plugin-storybook"

export default [
   // other config here
  ...eslintPluginStorybook.configs["flat/recommended"],
  // more config
]
```

**Comment by stevezhu** [comment]
Not sure if anyone is running into this, but it seems like only this change works for me when using `eslint-plugin-storybook@0.9.0--canary.156.da7873a.0`
```diff
     {
         name: 'storybook:recommended:stories-rules',
-        files: ['*.stories.@(ts|tsx|js|jsx|mjs|cjs)', '*.story.@(ts|tsx|js|jsx|mjs|cjs)'],
+        files: ['**/*.stories.@(ts|tsx|js|jsx|mjs|cjs)', '**/*.story.@(ts|tsx|js|jsx|mjs|cjs)'],
```

**Comment by kuschti** [comment]
> Not sure if anyone is running into this, but it seems I had to make this change when using `eslint-plugin-storybook@0.9.0--canary.156.da7873a.0` in `dist/configs/flat/recommended.js`
> 
> ```diff
>      {
>          name: 'storybook:recommended:stories-rules',
> -        files: ['*.stories.@(ts|tsx|js|jsx|mjs|cjs)', '*.story.@(ts|tsx|js|jsx|mjs|cjs)'],
> +        files: ['**/*.stories.@(ts|tsx|js|jsx|mjs|cjs)', '**/*.story.@(ts|tsx|js|jsx|mjs|cjs)'],
> ```

we have the same problem, it's already [mentioned](https://github.com/storybookjs/eslint-plugin-storybook/pull/156#discussion_r1654298539) in the flat-config PR #156

**Comment by maxpatiiuk** [comment]
Thank you for updating this package to support flat config.
However, I encountered an issue as this package depends on a very old version of `@typescript-eslint/utils` [`^5.62.0`](https://github.com/storybookjs/eslint-plugin-storybook/blob/da7873a47f33226407bac76db1ecc5f6c5b52ea7/package.json#L56).
That version of `@typescript-eslint/utils` does not support ESLint 9, which causes yarn dependency resolution to fail

**Comment by stevezhu** [comment]
> > Not sure if anyone is running into this, but it seems I had to make this change when using `eslint-plugin-storybook@0.9.0--canary.156.da7873a.0` in `dist/configs/flat/recommended.js`
> > ```diff
> >      {
> >          name: 'storybook:recommended:stories-rules',
> > -        files: ['*.stories.@(ts|tsx|js|jsx|mjs|cjs)', '*.story.@(ts|tsx|js|jsx|mjs|cjs)'],
> > +        files: ['**/*.stories.@(ts|tsx|js|jsx|mjs|cjs)', '**/*.story.@(ts|tsx|js|jsx|mjs|cjs)'],
> > ```
> 
> we have the same problem, it's already [mentioned](https://github.com/storybookjs/eslint-plugin-storybook/pull/156#discussion_r1654298539) in the flat-config PR #156

Ah great didn't catch that, thanks!
