### ISSUE TITLE
CSF-strict config should include CSF config

### ISSUE THREAD

**Issue by AndreaPontrandolfo** [storybookjs/eslint-plugin-storybook#178]
CSF-strict doesn't include the base CSF config. This is inconvenient and inconsistent with how other libs in the ecosystem does this (like typescript-eslint, for example).

**Describe the solution you'd like**
CSF-strict config should include CSF config.

**Comment by AndreaPontrandolfo** [comment]
Looking at the code it looks like this is already the case, it's just very very unclear by the docs.

**Comment by yannbf** [comment]
Hey @AndreaPontrandolfo thanks for reporting this. It's quite valid, the fact that the docs are unclear are worth making changes! It's done now, I hope it's more clear to you 🙏
