### ISSUE TITLE
Support .jsx extension

### ISSUE THREAD

**Issue by mharward-tw** [storybookjs/eslint-plugin-storybook#59]
At the moment, this plugin does not support .jsx extension, which is commonly used for react projects. This leads to the plugin not being usable in projects that use this convention.

As a dev who would love to use this to ensure consistency in our .stories.jsx files, adding this extension would be very useful.

Change would require adding the extension into https://github.com/storybookjs/eslint-plugin-storybook/blob/0c413c9497b487234356b5dca0f460f98ce6c108/tools/update-configs.ts

**Comment by yannbf** [comment]
Hey @mharward-tw thank you so much for catching that! It was just overlooked. Could you please try version 0.5.2? Thank you!

**Comment by mharward-tw** [comment]
Thanks @yannbf, much appreciated and thank you for such a quick turn around. I've just checked the new version and it works like a charm! Thank you :)

**Comment by yannbf** [comment]
Alright awesome! Thanks once again and have a great one! I hope you like using this plugin and keep the feedback coming <3
