### ISSUE TITLE
documentation for `csf-component` contradicts `no-title-property-in-meta`?

### ISSUE THREAD

**Issue by ljosberinn** [storybookjs/eslint-plugin-storybook#70]
Right now, the examples for incorrect and correct code of [`csf-component`](https://github.com/storybookjs/eslint-plugin-storybook/blob/main/docs/rules/csf-component.md) have a `title` property.

[`no-title-in-property-meta`](https://github.com/storybookjs/eslint-plugin-storybook/blob/main/docs/rules/no-title-property-in-meta.md)  lints against it however. Is this circumstantially correct or is the example simply disregarding that?

**Comment by yannbf** [comment]
Hey @ljosberinn, these rules don't necessarily correlate. The idea of `no-title-in-property-meta` is to enforce using the auto title generation feature in a project to have consistency, but using custom titles is totally fine as well! You can get some more info in the [further reading](https://github.com/storybookjs/eslint-plugin-storybook/blob/main/docs/rules/no-title-property-in-meta.md#further-reading) section in the documentation of that rule.

**Comment by ljosberinn** [comment]
fair, kinda forgot about custom titles, thanks
