### ISSUE TITLE
await-interactions fixer insert await without inserting async

### ISSUE THREAD

**Issue by AMorgaut** [storybookjs/eslint-plugin-storybook#72]
**Describe the bug**

**To Reproduce**

1. Go to  *'docs/rules/[await-interactions.md](https://github.com/storybookjs/eslint-plugin-storybook/blob/main/docs/rules/await-interactions.md)'*
2. Copy the example of **incorrect** code 
3. Use the `await-interactions` rule fixer
4. The generated code is invalid JavaScript code that can not run (cf example of **correct** code)

```
import { within, userEvent } from '@storybook/testing-library'

MyStory.play = (context) => {
  const canvas = within(context.canvasElement)
  // awaited 👍
  await userEvent.click(canvas.getByRole('button'))
}
```

**Expected behavior**

In the fixed code, the `MyStory.play` method should be defined changed to `async`:
```
MyStory.play = async (context) => {
  const canvas = within(context.canvasElement)
  // awaited 👍
  await userEvent.click(canvas.getByRole('button'))
}
```

**Screenshots**

![image](https://user-images.githubusercontent.com/49318/147931975-755d79b9-4f1f-423a-a621-7ee313985c78.png)

**Comment by yannbf** [comment]
This was fixed in [v0.5.7](https://github.com/storybookjs/eslint-plugin-storybook/releases/tag/v0.5.7). Thanks for opening this issue!
