### ISSUE TITLE
New Rule: Disallow template strings in titles

### ISSUE THREAD

**Issue by IanVS** [storybookjs/eslint-plugin-storybook#74]
**Is your feature request related to a problem? Please describe.**
According to https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#string-literal-titles, dynamic titles are going to be prohibited in 7.0.  It might be nice to have a linting rule that flags if backticks are being used.

**Describe the solution you'd like**
A rule, not included in recommended (due to different versions of storybook having different requirements), which flags the use of backticks in story titles.

**Additional context**
https://discord.com/channels/486522875931656193/691505730125168682/928685457552863254

![image](https://user-images.githubusercontent.com/4616705/148416378-c00a9069-30b4-41d7-8d7e-67b5240f4f51.png)

**Comment by YozhEzhi** [comment]
> recommended (due to different versions of storybook having different requirements)

I prefer the rule to be error. Because dynamic title is blocking using of ["on demand feature"](https://storybook.js.org/blog/storybook-on-demand-architecture/#:~:text=CSF%20titles%20and,)).

**Comment by IanVS** [comment]
Closing in preference to https://github.com/storybookjs/eslint-plugin-storybook/issues/111
