### ISSUE TITLE
Latest version of `@typescript-eslint/experimental-utils` breaks the ast-utils import

### ISSUE THREAD

**Issue by tombakerjr** [storybookjs/eslint-plugin-storybook#75]
**Describe the bug**
The maintainers of `@typescript-eslint/experimental-utils` renamed the package to `@typescript-eslint/utils` in this release https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/experimental-utils/CHANGELOG.md#5100-2022-01-17, which seems to break the following imports in this plugin:
* https://github.com/storybookjs/eslint-plugin-storybook/blob/main/lib/utils/index.ts#L3
* https://github.com/storybookjs/eslint-plugin-storybook/blob/main/lib/rules/prefer-pascal-case.ts#L6

I believe this can be fixed by switching to what appears to be the intended import: https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/utils/src/index.ts#L1

**To Reproduce**
1. Run `yarn upgrade`
2. Attempt to run `yarn build-storybook`
3. See error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/15802192/149852348-710f4eff-2829-48a7-8a8d-5b011352db56.png)

**Additional context**

**Comment by yannbf** [comment]
This should be fixed in `v0.5.6`. Thanks for your work @tombakerjr !!
