### ISSUE TITLE
Support for "stories.*" pattern

### ISSUE THREAD

**Issue by sogame** [storybookjs/eslint-plugin-storybook#77]
**Is your feature request related to a problem? Please describe.**
In my project we use the filename `stories.jsx` instead of `ComponentName.stories.jsx`, and as mentioned in the readme, this plugin only supports the patterns `*.stories.*` and `*.story.*`.

**Describe the solution you'd like**
I would like to check if it would be possible to add support for the pattern `stories.*`.

**Describe alternatives you've considered**
We could rename all our stories files, but using `stories.jsx` is simpler in our case, and given all components are in their own folder there's no risk of having more than one stories file in each folder.

**Comment by yannbf** [comment]
Hey @sogame thanks for opening this issue!

This is an interesting question. The eslint plugin is about good practices and consistency between multiple projects that use Storybook. Your use case is the first I've seen that does not follow the naming convention. 

I'd say you could do one of the following:

1 - Rename your `stories.jsx` files to `index.stories.jsx` or `ComponentName.stories.jsx`. That would fix it.
Cons: A bit of manual effort
Pros: You follow the same convention as most of the Storybook projects, which is widely used in our documentation, blog posts, community content, etc. This also gets rule changes/new rules once you update the library.

2 - Add an override to your `eslintrc.js` file that sets all rules you'd like (the following ones are part of the recommended pack):
```js
{
  "overrides": [
    {
      "files": ['stories.jsx'],
      "rules": {
        "storybook/await-interactions": "error",
        "storybook/context-in-play-function": "error",
        "storybook/default-exports": "error",
        "storybook/hierarchy-separator": "warn",
        "storybook/no-redundant-story-name": "warn",
        "storybook/prefer-pascal-case": "warn",
        "storybook/story-exports": "error",
        "storybook/use-storybook-expect": "error",
        "storybook/use-storybook-testing-library": "error"
      }
    }
  ]
}
```

Cons: The set of rules and configs is fixed and won't be updated once you update this library (although the rules for *.stories.jsx will still be in effect and get updated)
Pros: You keep your naming convention and get a more explicit list of rules, which will give you better control.

**Comment by sogame** [comment]
> The eslint plugin is about good practices and consistency

That's exactly why I would like to start using this plugin, to make sure we follow the best practices 😬 

I tried to search if there was any reference to naming convention in Storybook docs and I couldn't find any. It's true the docs always use `ComponentName.stories.jsx`, but I wasn't sure it's a requirement/convention.

Using `index.stories.jsx` feels a bit hacky 😅
I would definitely go for `ComponentName.stories.jsx` (although it's a bit verbose, that's why we used `stories.jsx` instead) if the plugin can't be updated to allow for `stories.*`.

Personally, I think allowing `stories.*` gives more flexibility to users, but if that pattern is against the standard, I totally understand :-)
In this case, though, do you think it would make sense to add a rule that doesn't allow `stories.*`? Asking because it could lead to a false sense of security: initially I though our stories had no issues, until I realised the files weren't being analysed due to the name 😅
