### ISSUE TITLE
awaited chain expression is seen as invalid

### ISSUE THREAD

**Issue by VinceMalone** [storybookjs/eslint-plugin-storybook#86]
**Describe the bug**

with the `await-interaction` rule enabled, if a play function is being composed from another story, but the expression has an optional chain, it's seen as invalid; even if it's correctly awaited. because the expression will be seen as false and the auto-fix doesn't fix it; instead many redundant awaits are added.

**To Reproduce**

1. lint the following code with the `await-interaction` enabled

   ```js
   export const SecondStory = {
     play: async (context) => {
       await FirstStory.play?.(context)
     }
   }
   ```

2. run auto-fix

**Expected behavior**

it should be seen as valid and the auto-fix shouldn't alter the code

**Screenshots**

valid code is seen as invalid: <img width="751" alt="image" src="https://user-images.githubusercontent.com/2516349/160834150-bca0cbd7-e7df-48bb-baf6-87889adca8dd.png">

post auto-fix: <img width="925" alt="image" src="https://user-images.githubusercontent.com/2516349/160833221-70e8bf50-e2a0-4fbe-baff-dee145d37fa8.png">

**Comment by yannbf** [comment]
This was released in [v0.5.9](https://github.com/storybookjs/eslint-plugin-storybook/releases/tag/v0.5.9)! Thanks once again for your contribution @VinceMalone !
