### ISSUE TITLE
Specify a Licence

### ISSUE THREAD

**Issue by jiminycricket** [storybookjs/eslint-plugin-storybook#92]
**Is your feature request related to a problem? Please describe.**
Really great eslint plugin and totally agree it will makes my codebase better. 
I would like to use it but I couldn't find a LICENSE file.

**Describe the solution you'd like**
Add a LICENSE file

**Describe alternatives you've considered**
declaration in README.MD

**Comment by yannbf** [comment]
Hey @jiminycricket thanks for opening this issue! The license is added now.

**Comment by jiminycricket** [comment]
Thanks @yannbf
