### ISSUE TITLE
`storybook/no-uninstalled-addons` fails with locally references file addons

### ISSUE THREAD

**Issue by alopix** [storybookjs/eslint-plugin-storybook#97]
**Describe the bug**

The latest version 0.6.0 introduces `storybook/no-uninstalled-addons` which will fail if you use file path addons.

> [eslint] storybook/main.js
> [eslint]   91:5  error  
> The ./my-addon/preset.cjs is not installed. Did you forget to install it?  storybook/no-uninstalled-addons

**To Reproduce**
1. Add an addon to your `main.js` array using a relative file path, e.g. `addons: ['./my-addon/preset.cjs']`
2. Run eslint
3. See error

**Expected behavior**
Local file references should be ignored since there is no need to install them.

**Comment by yannbf** [comment]
Hey @alopix thanks for surfacing this! We'll take that into account and come up with a fix. cc @andrelas1

**Comment by yannbf** [comment]
Hey @alopix I just released [v0.6.1](https://github.com/storybookjs/eslint-plugin-storybook/releases/tag/v0.6.1) containing a fix for this. Thank you so much for helping make this happen!

**Comment by yannbf** [comment]
Thank you for using this plugin and more so for creating this issue!
